GRID_SIZE: 10
GRID_X: 100
GRID_Y: 100
MARGIN: 2
COLORS:
  - GRAY:
      - 169
      - 169
      - 169
  - BLACK:
      - 0
      - 0
      - 0
  - GREEN:
      - 0
      - 255
      - 0
  - RED:
      - 255
      - 0
      - 0
  - BLUE:
      - 0
      - 0
      - 255
  - CYAN:
      - 0
      - 204
      - 204
  - PINK:
      - 255
      - 105
      - 180
percentChanceForWall: 40
actualPercentOfWalls: 0
weight: 100
weightDelta: 10