GRID_SIZE: 30
GRID_X: 20
GRID_Y: 20
MARGIN: 2
COLORS:
  - GRAY:
      - 169
      - 169
      - 169
  - BLACK:
      - 0
      - 0
      - 0
  - GREEN:
      - 0
      - 255
      - 0
  - RED:
      - 255
      - 0
      - 0
  - BLUE:
      - 0
      - 0
      - 255
  - CYAN:
      - 0
      - 204
      - 204
  - PINK:
      - 255
      - 105
      - 180
percentChanceForWall: 10
actualPercentOfWalls: 0
weight: 20